name: form_fields
version: 1.1.0
author: Roland Volskaya
homepage: github.com/volskaya/form_fields.dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  json_annotation: ^4.0.1
  freezed_annotation: ^0.14.1
  provider: ^5.0.0
  file_picker: ^3.0.1

  firebase_image:
    path: /home/projects/packages/firebase_image
  utils:
    path: /home/projects/packages/flutter_helpers/utils
  scrollable_positioned_list:
    path: /home/projects/packages/flutter_helpers/scrollable_positioned_list
  material_dialog:
    path: /home/projects/packages/flutter_helpers/material_dialog
  country_catalog:
    path: /home/projects/packages/country_catalog

dev_dependencies:
  build_runner:
  json_serializable: ^5.0.0
  freezed: ^0.14.1+1

dependency_overrides:
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen

flutter:
  generate: true
