name: form_fields
version: 1.0.0
author: Roland Volskaya
homepage: github.com/volskaya/form_fields.dart
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  json_annotation:
  image_picker: ^0.6.7+4
  freezed: ^0.12.6

  firebase_image:
    path: /home/projects/packages/firebase_image
  utils:
    path: /home/projects/packages/flutter_helpers/utils
  scrollable_positioned_list:
    path: /home/projects/packages/flutter_helpers/scrollable_positioned_list
  material_dialog:
    path: /home/projects/packages/flutter_helpers/material_dialog
  country_catalog:
    path: /home/projects/packages/country_catalog

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable:
  build_runner: ^1.10.0
  freezed_annotation: ^0.12.0

dependency_overrides:
  intl: 0.17.0
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen

flutter:
  generate: true
  assets:
    - packages/form_fields/flags/ad.png
    - packages/form_fields/flags/ae.png
    - packages/form_fields/flags/af.png
    - packages/form_fields/flags/ag.png
    - packages/form_fields/flags/ai.png
    - packages/form_fields/flags/al.png
    - packages/form_fields/flags/am.png
    - packages/form_fields/flags/an.png
    - packages/form_fields/flags/ao.png
    - packages/form_fields/flags/aq.png
    - packages/form_fields/flags/ar.png
    - packages/form_fields/flags/as.png
    - packages/form_fields/flags/at.png
    - packages/form_fields/flags/au.png
    - packages/form_fields/flags/aw.png
    - packages/form_fields/flags/ax.png
    - packages/form_fields/flags/az.png
    - packages/form_fields/flags/ba.png
    - packages/form_fields/flags/bb.png
    - packages/form_fields/flags/bd.png
    - packages/form_fields/flags/be.png
    - packages/form_fields/flags/bf.png
    - packages/form_fields/flags/bg.png
    - packages/form_fields/flags/bh.png
    - packages/form_fields/flags/bi.png
    - packages/form_fields/flags/bj.png
    - packages/form_fields/flags/bl.png
    - packages/form_fields/flags/bm.png
    - packages/form_fields/flags/bn.png
    - packages/form_fields/flags/bo.png
    - packages/form_fields/flags/bq.png
    - packages/form_fields/flags/br.png
    - packages/form_fields/flags/bs.png
    - packages/form_fields/flags/bt.png
    - packages/form_fields/flags/bv.png
    - packages/form_fields/flags/bw.png
    - packages/form_fields/flags/by.png
    - packages/form_fields/flags/bz.png
    - packages/form_fields/flags/ca.png
    - packages/form_fields/flags/cc.png
    - packages/form_fields/flags/cd.png
    - packages/form_fields/flags/cf.png
    - packages/form_fields/flags/cg.png
    - packages/form_fields/flags/ch.png
    - packages/form_fields/flags/ci.png
    - packages/form_fields/flags/ck.png
    - packages/form_fields/flags/cl.png
    - packages/form_fields/flags/cm.png
    - packages/form_fields/flags/cn.png
    - packages/form_fields/flags/co.png
    - packages/form_fields/flags/cr.png
    - packages/form_fields/flags/cu.png
    - packages/form_fields/flags/cv.png
    - packages/form_fields/flags/cw.png
    - packages/form_fields/flags/cx.png
    - packages/form_fields/flags/cy.png
    - packages/form_fields/flags/cz.png
    - packages/form_fields/flags/de.png
    - packages/form_fields/flags/dj.png
    - packages/form_fields/flags/dk.png
    - packages/form_fields/flags/dm.png
    - packages/form_fields/flags/do.png
    - packages/form_fields/flags/dz.png
    - packages/form_fields/flags/ec.png
    - packages/form_fields/flags/ee.png
    - packages/form_fields/flags/eg.png
    - packages/form_fields/flags/eh.png
    - packages/form_fields/flags/er.png
    - packages/form_fields/flags/es.png
    - packages/form_fields/flags/et.png
    - packages/form_fields/flags/eu.png
    - packages/form_fields/flags/fi.png
    - packages/form_fields/flags/fj.png
    - packages/form_fields/flags/fk.png
    - packages/form_fields/flags/fm.png
    - packages/form_fields/flags/fo.png
    - packages/form_fields/flags/fr.png
    - packages/form_fields/flags/ga.png
    - packages/form_fields/flags/gb-eng.png
    - packages/form_fields/flags/gb-nir.png
    - packages/form_fields/flags/gb.png
    - packages/form_fields/flags/gb-sct.png
    - packages/form_fields/flags/gb-wls.png
    - packages/form_fields/flags/gd.png
    - packages/form_fields/flags/ge.png
    - packages/form_fields/flags/gf.png
    - packages/form_fields/flags/gg.png
    - packages/form_fields/flags/gh.png
    - packages/form_fields/flags/gi.png
    - packages/form_fields/flags/gl.png
    - packages/form_fields/flags/gm.png
    - packages/form_fields/flags/gn.png
    - packages/form_fields/flags/gp.png
    - packages/form_fields/flags/gq.png
    - packages/form_fields/flags/gr.png
    - packages/form_fields/flags/gs.png
    - packages/form_fields/flags/gt.png
    - packages/form_fields/flags/gu.png
    - packages/form_fields/flags/gw.png
    - packages/form_fields/flags/gy.png
    - packages/form_fields/flags/hk.png
    - packages/form_fields/flags/hm.png
    - packages/form_fields/flags/hn.png
    - packages/form_fields/flags/hr.png
    - packages/form_fields/flags/ht.png
    - packages/form_fields/flags/hu.png
    - packages/form_fields/flags/id.png
    - packages/form_fields/flags/ie.png
    - packages/form_fields/flags/il.png
    - packages/form_fields/flags/im.png
    - packages/form_fields/flags/in.png
    - packages/form_fields/flags/io.png
    - packages/form_fields/flags/iq.png
    - packages/form_fields/flags/ir.png
    - packages/form_fields/flags/is.png
    - packages/form_fields/flags/it.png
    - packages/form_fields/flags/je.png
    - packages/form_fields/flags/jm.png
    - packages/form_fields/flags/jo.png
    - packages/form_fields/flags/jp.png
    - packages/form_fields/flags/ke.png
    - packages/form_fields/flags/kg.png
    - packages/form_fields/flags/kh.png
    - packages/form_fields/flags/ki.png
    - packages/form_fields/flags/km.png
    - packages/form_fields/flags/kn.png
    - packages/form_fields/flags/kp.png
    - packages/form_fields/flags/kr.png
    - packages/form_fields/flags/kw.png
    - packages/form_fields/flags/ky.png
    - packages/form_fields/flags/kz.png
    - packages/form_fields/flags/la.png
    - packages/form_fields/flags/lb.png
    - packages/form_fields/flags/lc.png
    - packages/form_fields/flags/li.png
    - packages/form_fields/flags/lk.png
    - packages/form_fields/flags/lr.png
    - packages/form_fields/flags/ls.png
    - packages/form_fields/flags/lt.png
    - packages/form_fields/flags/lu.png
    - packages/form_fields/flags/lv.png
    - packages/form_fields/flags/ly.png
    - packages/form_fields/flags/ma.png
    - packages/form_fields/flags/mc.png
    - packages/form_fields/flags/md.png
    - packages/form_fields/flags/me.png
    - packages/form_fields/flags/mf.png
    - packages/form_fields/flags/mg.png
    - packages/form_fields/flags/mh.png
    - packages/form_fields/flags/mk.png
    - packages/form_fields/flags/ml.png
    - packages/form_fields/flags/mm.png
    - packages/form_fields/flags/mn.png
    - packages/form_fields/flags/mo.png
    - packages/form_fields/flags/mp.png
    - packages/form_fields/flags/mq.png
    - packages/form_fields/flags/mr.png
    - packages/form_fields/flags/ms.png
    - packages/form_fields/flags/mt.png
    - packages/form_fields/flags/mu.png
    - packages/form_fields/flags/mv.png
    - packages/form_fields/flags/mw.png
    - packages/form_fields/flags/mx.png
    - packages/form_fields/flags/my.png
    - packages/form_fields/flags/mz.png
    - packages/form_fields/flags/na.png
    - packages/form_fields/flags/nc.png
    - packages/form_fields/flags/ne.png
    - packages/form_fields/flags/nf.png
    - packages/form_fields/flags/ng.png
    - packages/form_fields/flags/ni.png
    - packages/form_fields/flags/nl.png
    - packages/form_fields/flags/no.png
    - packages/form_fields/flags/np.png
    - packages/form_fields/flags/nr.png
    - packages/form_fields/flags/nu.png
    - packages/form_fields/flags/nz.png
    - packages/form_fields/flags/om.png
    - packages/form_fields/flags/pa.png
    - packages/form_fields/flags/pe.png
    - packages/form_fields/flags/pf.png
    - packages/form_fields/flags/pg.png
    - packages/form_fields/flags/ph.png
    - packages/form_fields/flags/pk.png
    - packages/form_fields/flags/pl.png
    - packages/form_fields/flags/pm.png
    - packages/form_fields/flags/pn.png
    - packages/form_fields/flags/pr.png
    - packages/form_fields/flags/ps.png
    - packages/form_fields/flags/pt.png
    - packages/form_fields/flags/pw.png
    - packages/form_fields/flags/py.png
    - packages/form_fields/flags/qa.png
    - packages/form_fields/flags/re.png
    - packages/form_fields/flags/ro.png
    - packages/form_fields/flags/rs.png
    - packages/form_fields/flags/ru.png
    - packages/form_fields/flags/rw.png
    - packages/form_fields/flags/sa.png
    - packages/form_fields/flags/sb.png
    - packages/form_fields/flags/sc.png
    - packages/form_fields/flags/sd.png
    - packages/form_fields/flags/se.png
    - packages/form_fields/flags/sg.png
    - packages/form_fields/flags/sh.png
    - packages/form_fields/flags/si.png
    - packages/form_fields/flags/sj.png
    - packages/form_fields/flags/sk.png
    - packages/form_fields/flags/sl.png
    - packages/form_fields/flags/sm.png
    - packages/form_fields/flags/sn.png
    - packages/form_fields/flags/so.png
    - packages/form_fields/flags/sr.png
    - packages/form_fields/flags/ss.png
    - packages/form_fields/flags/st.png
    - packages/form_fields/flags/sv.png
    - packages/form_fields/flags/sx.png
    - packages/form_fields/flags/sy.png
    - packages/form_fields/flags/sz.png
    - packages/form_fields/flags/tc.png
    - packages/form_fields/flags/td.png
    - packages/form_fields/flags/tf.png
    - packages/form_fields/flags/tg.png
    - packages/form_fields/flags/th.png
    - packages/form_fields/flags/tj.png
    - packages/form_fields/flags/tk.png
    - packages/form_fields/flags/tl.png
    - packages/form_fields/flags/tm.png
    - packages/form_fields/flags/tn.png
    - packages/form_fields/flags/to.png
    - packages/form_fields/flags/tr.png
    - packages/form_fields/flags/tt.png
    - packages/form_fields/flags/tv.png
    - packages/form_fields/flags/tw.png
    - packages/form_fields/flags/tz.png
    - packages/form_fields/flags/ua.png
    - packages/form_fields/flags/ug.png
    - packages/form_fields/flags/um.png
    - packages/form_fields/flags/us.png
    - packages/form_fields/flags/uy.png
    - packages/form_fields/flags/uz.png
    - packages/form_fields/flags/va.png
    - packages/form_fields/flags/vc.png
    - packages/form_fields/flags/ve.png
    - packages/form_fields/flags/vg.png
    - packages/form_fields/flags/vi.png
    - packages/form_fields/flags/vn.png
    - packages/form_fields/flags/vu.png
    - packages/form_fields/flags/wf.png
    - packages/form_fields/flags/ws.png
    - packages/form_fields/flags/xk.png
    - packages/form_fields/flags/ye.png
    - packages/form_fields/flags/yt.png
    - packages/form_fields/flags/za.png
    - packages/form_fields/flags/zm.png
    - packages/form_fields/flags/zw.png
